# Practice 2

In [2]:
import numpy as np

## 1.1

### Task 1.3.1

In [8]:
chess = np.zeros((8, 8))

for i in range(8):
    for j in range(8):
        chess[i, j] = (i % 2 == 0 and j % 2 == 1) or (i % 2 == 1 and j % 2 == 0)

print(chess)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


### Task 1.3.2

In [11]:
arr = np.array([np.arange(0, 5) for i in range(5)])
print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### Task 1.3.3

In [12]:
arr = np.random.random((3, 3, 3))
print(arr)

[[[0.19085323 0.53652069 0.15614   ]
  [0.45176232 0.38569618 0.86994411]
  [0.75077912 0.6077747  0.62717636]]

 [[0.39148543 0.34746577 0.94851424]
  [0.02825765 0.34225428 0.58206025]
  [0.23861662 0.5982946  0.96747405]]

 [[0.00699125 0.83005221 0.19568544]
  [0.23644813 0.10221488 0.14731638]
  [0.50258139 0.51740302 0.40287335]]]


### Task 1.3.4

In [14]:
r, c = 5, 6
arr = np.zeros((r, c))

for i in range(r):
    for j in range(c):
        if i == 0 or j == 0 or i == r - 1 or j == c - 1:
            arr[i, j] = 1

print(arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


### Task 1.3.5

In [17]:
arr = np.random.rand(3, 3)

arr = -1 * np.sort(-arr)

print(arr)

[[0.89522414 0.7657289  0.08589993]
 [0.62258719 0.3881745  0.37022159]
 [0.46857714 0.44506371 0.36578524]]


### Task 1.3.6

In [20]:
arr = np.random.rand(7, 6)

print(f'Shape: {arr.shape} | Size: {arr.size} | Dim: {arr.ndim}')

Shape: (7, 6) | Size: 42 | Dim: 2
