# Practice 2

In [2]:
import numpy as np

## 1.1

### Task 1.3.1

In [3]:
chess = np.zeros((8, 8))

for i in range(8):
    for j in range(8):
        chess[i, j] = (i % 2 == 0 and j % 2 == 1) or (i % 2 == 1 and j % 2 == 0)

print(chess)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


### Task 1.3.2

In [4]:
arr = np.array([np.arange(0, 5) for i in range(5)])
print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### Task 1.3.3

In [5]:
arr = np.random.random((3, 3, 3))
print(arr)

[[[0.2102906  0.20514523 0.08370293]
  [0.53349884 0.39974814 0.75919807]
  [0.51392276 0.83251569 0.25479557]]

 [[0.05711506 0.19375191 0.9204523 ]
  [0.36941602 0.71284277 0.51429878]
  [0.12499829 0.2476554  0.94298277]]

 [[0.93682754 0.70900374 0.58115642]
  [0.9053372  0.67714727 0.33896663]
  [0.83526215 0.15117603 0.23521023]]]


### Task 1.3.4

In [6]:
r, c = 5, 6
arr = np.zeros((r, c))

for i in range(r):
    for j in range(c):
        if i == 0 or j == 0 or i == r - 1 or j == c - 1:
            arr[i, j] = 1

print(arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


### Task 1.3.5

In [7]:
arr = np.random.rand(3, 3)

arr = -1 * np.sort(-arr)

print(arr)

[[0.94715515 0.84730198 0.78686638]
 [0.93773221 0.63904799 0.18031415]
 [0.97790814 0.5222078  0.41536716]]


### Task 1.3.6

In [8]:
arr = np.random.rand(7, 6)

print(f'Shape: {arr.shape} | Size: {arr.size} | Dim: {arr.ndim}')

Shape: (7, 6) | Size: 42 | Dim: 2


## 2.1 - Pandas

In [9]:
import pandas as pd

### Task 2.3.1

In [11]:
x = pd.Series([1, 2, 3, 4, 5])
y = pd.Series([6, 7, 8, 9, 10])

dist = np.sqrt(np.sum([(a-b)*(a-b) for a, b in zip(x, y)]))

print("Euclidean distance between two series is:", dist)

Euclidean distance between two series is: 11.180339887498949


### Task 2.3.2

In [28]:
url = "https://raw.githubusercontent.com/akmand/datasets/main/boston_housing.csv"

dataframe = pd.read_csv(url)

dataframe.head(5)

crim    zn  indus  chas    nox     rm   age    dis  rad  tax  ptratio  \
0  0.006  18.0   2.31     0  0.538  6.575  65.2  4.090    1  296     15.3   
1  0.027   0.0   7.07     0  0.469  6.421  78.9  4.967    2  242     17.8   
2  0.027   0.0   7.07     0  0.469  7.185  61.1  4.967    2  242     17.8   
3  0.032   0.0   2.18     0  0.458  6.998  45.8  6.062    3  222     18.7   
4  0.069   0.0   2.18     0  0.458  7.147  54.2  6.062    3  222     18.7   

    bbtown  lstat  medv  
0  396.898   4.98  24.0  
1  396.898   9.14  21.6  
2  392.828   4.03  34.7  
3  394.629   2.94  33.4  
4  396.898   5.33  36.2

### Task 2.3.3

In [29]:
dataframe.head(2)

crim    zn  indus  chas    nox     rm   age    dis  rad  tax  ptratio  \
0  0.006  18.0   2.31     0  0.538  6.575  65.2  4.090    1  296     15.3   
1  0.027   0.0   7.07     0  0.469  6.421  78.9  4.967    2  242     17.8   

    bbtown  lstat  medv  
0  396.898   4.98  24.0  
1  396.898   9.14  21.6

In [30]:
dataframe.tail(3)

crim   zn  indus  chas    nox     rm   age    dis  rad  tax  ptratio  \
503  0.061  0.0  11.93     0  0.573  6.976  91.0  2.167    1  273     21.0   
504  0.110  0.0  11.93     0  0.573  6.794  89.3  2.389    1  273     21.0   
505  0.047  0.0  11.93     0  0.573  6.030  80.8  2.505    1  273     21.0   

      bbtown  lstat  medv  
503  396.898   5.64  23.9  
504  393.449   6.48  22.0  
505  396.898   7.88  11.9

In [31]:
print(dataframe.shape)

(506, 14)


In [32]:
dataframe.describe()

crim          zn       indus        chas         nox          rm  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613512   11.363636   11.136779    0.069170    0.554696    6.284634   
std      8.601528   23.322453    6.860353    0.253994    0.115877    0.702617   
min      0.006000    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082000    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256500    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677000   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976000  100.000000   27.740000    1.000000    0.871000    8.780000   

              age         dis         rad         tax     ptratio      bbtown  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.794998    9.549407  408.237154   18.455534  356.672931   
std     28.148861    2.105720    8.707259  168.537116    2.164946   91.294513   
min      2.900000    1.130000    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100250    4.000000  279.000000   17.400000  375.376000   
50%     77.500000    3.207500    5.000000  330.000000   19.050000  391.439500   
75%     94.075000    5.188500   24.000000  666.000000   20.200000  396.224000   
max    100.000000   12.126000   24.000000  711.000000   22.000000  396.898000   

            lstat        medv  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [33]:
dataframe.iloc[1:4]

crim   zn  indus  chas    nox     rm   age    dis  rad  tax  ptratio  \
1  0.027  0.0   7.07     0  0.469  6.421  78.9  4.967    2  242     17.8   
2  0.027  0.0   7.07     0  0.469  7.185  61.1  4.967    2  242     17.8   
3  0.032  0.0   2.18     0  0.458  6.998  45.8  6.062    3  222     18.7   

    bbtown  lstat  medv  
1  396.898   9.14  21.6  
2  392.828   4.03  34.7  
3  394.629   2.94  33.4

In [34]:
dataframe[dataframe['rad'] == 1].head(2)

crim    zn  indus  chas    nox     rm   age   dis  rad  tax  ptratio  \
0    0.006  18.0   2.31     0  0.538  6.575  65.2  4.09    1  296     15.3   
193  0.022  60.0   2.93     0  0.401  6.800   9.9  6.22    1  265     15.6   

      bbtown  lstat  medv  
0    396.898   4.98  24.0  
193  393.369   5.03  31.1

## 3.1 - Working with numerical data

In [36]:
from sklearn import preprocessing

### Task 3.3.2

In [35]:
url = "https://raw.githubusercontent.com/akmand/datasets/master/iris.csv"

dataframe = pd.read_csv(url)

dataframe.head(5)

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa
3              4.6             3.1              1.5             0.2  setosa
4              5.0             3.6              1.4             0.2  setosa

In [50]:
scaler = preprocessing.MinMaxScaler()

dataframe['sepal_length_cm'] = scaler.fit_transform(dataframe[['sepal_length_cm']])
dataframe['sepal_length_cm'].head(5)

0    0.222222
1    0.166667
2    0.111111
3    0.083333
4    0.194444
Name: sepal_length_cm, dtype: float64

In [52]:
scaler = preprocessing.StandardScaler()

dataframe['sepal_width_cm'] = scaler.fit_transform(dataframe[['sepal_width_cm']])
dataframe['sepal_width_cm'].head(5)

0    1.032057
1   -0.124958
2    0.337848
3    0.106445
4    1.263460
Name: sepal_width_cm, dtype: float64